spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journal_entries?replicaSet=rs0
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal

logging:
  level:
    net:
      engineeringdigest:
        journalApp: INFO