#How to use profiles in spring boot
#**Spring Profiles** are a way to separate configuration for different environments
spring:
  profiles:
    active: dev

weather.api.key: 23cb378a0dcc458aa8a165327260301