#How to use profiles in spring boot
#**Spring Profiles** are a way to separate configuration for different environments
spring:
  profiles:
    active: dev

  #ðŸ”¹ host & port â†’ SMTP server details
  #ðŸ”¹ username & password â†’ sender credentials
  #ðŸ”¹ starttls â†’ enables secure email transmission

  mail:
    host: smtp.gmail.com
    port: 587
    username: tusharpsomvanshi@gmail.com
    password: ukue trln wucw vzra
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ðŸ”¹ Redis config:
  redis:
    host: localhost
    port: 6379

#ukue trln wucw vzra
weather.api.key: 23cb378a0dcc458aa8a165327260301