spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journal_entries?replicaSet=rs0
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal

#At root level
#logging:
#  level:
#    root: ERROR / OFF

logging:
  level:
    net:
      engineeringdigest:
        journalApp: DEBUG

